Website = ""

[Details]
  Icon    = "../../assets/icon.png"
  Name    = "PassIt"
  ID      = "com.p4tin.passit"
  Version = "1.0.0"
  Build   = 1

  [Details.MacOS]
    Category = "public.app-category.utilities"
